spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/osanhaneat
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
jwt:
  privateKey: kPkym0Rmka4KmTCoko9Kk2k3dwC3vdImTTj+L13AWNE=
fileUpload:
  rootPath: C:\Users\dinht\OneDrive - dinhhung.vn\Desktop\uploads